"""Compare a look-ahead-prone same-bar signal with a delayed signal."""

from __future__ import annotations

import pandas as pd


def strategy_equity(prices: pd.Series, delayed: bool, cost_rate: float = 0.001) -> pd.Series:
    returns = prices.pct_change(fill_method=None).fillna(0.0)
    signal = (prices > prices.rolling(3).mean()).astype(float)
    position = signal.shift(1).fillna(0.0) if delayed else signal
    turnover = position.diff().abs().fillna(position.abs())
    net_returns = position * returns - turnover * cost_rate
    return 100_000 * (1 + net_returns).cumprod()


def main() -> None:
    dates = pd.bdate_range("2026-02-02", periods=10)
    prices = pd.Series([100, 104, 101, 108, 102, 111, 105, 115, 108, 118], index=dates)
    same_bar = strategy_equity(prices, delayed=False)
    delayed = strategy_equity(prices, delayed=True)

    print("same-bar final equity:", round(float(same_bar.iloc[-1]), 2))
    print("delayed final equity:", round(float(delayed.iloc[-1]), 2))
    print("lesson: a signal generated by today's close must not trade at that same close.")
    print("DEMO_OK")


if __name__ == "__main__":
    main()
