export interface ConceptLesson {
  mentalModel: string
  deepDive: string[]
  visualTitle: string
  flow: Array<{ title: string; detail: string }>
  exampleTitle: string
  example: string
  code?: string
  pitfalls: string[]
  practice: string[]
}

export const conceptLessons: Record<string, ConceptLesson> = {
  'quant-map:0': {
    mentalModel: '把量化研究想成一条科学实验流水线：先提出能被否定的假设，再固定数据、规则和评价方法，最后让历史与样本外数据回答问题。',
    deepDive: [
      '“过去 20 日涨得多的股票未来可能继续强势”是一条假设；“买宁德时代”只是一个结论。前者可以被写成窗口、排序、调仓频率和成本规则，后者无法稳定复现。量化工作的价值在于把人的直觉变成别人也能运行的实验。',
      '策略收益只是结果的一列。研究者还要检查最大回撤、换手、行业集中度、成交可行性和不同年份的稳定性。只要信号使用了当时未知的数据，再漂亮的曲线也没有研究价值。',
    ],
    visualTitle: '一个可复现的量化研究闭环',
    flow: [
      { title: '假设', detail: '先写经济逻辑与失败条件' },
      { title: '数据', detail: '明确来源、时点与可用范围' },
      { title: '规则', detail: '因子、仓位、成本和执行时刻' },
      { title: '验证', detail: '基准、样本外与稳健性检查' },
      { title: '结论', detail: '接受、否定或保留假设' },
    ],
    exampleTitle: '本项目如何体现',
    example: '策略实验室把动量、财务质量和情绪权重保存为配置；回测服务再用同一份配置生成资金曲线。改变参数会留下新的实验结果，而不是覆盖旧结论。',
    pitfalls: ['把一次赚钱等同于策略有效', '先看结果再补写假设', '只报告年化收益，不报告回撤与成本'],
    practice: ['用一句“如果…那么…”写下一个可证伪假设', '为假设补充一个明确的失败判据'],
  },
  'quant-map:1': {
    mentalModel: 'AI 是研究系统中的工具层，不是替你承担责任的“自动赚钱大脑”。不同角色需要不同的验证标准。',
    deepDive: [
      '开发辅助角色帮助生成代码、解释错误和补测试；信息抽取角色把新闻、公告等非结构化文本变成结构化字段；预测角色直接输出未来收益或类别。越靠近交易决策，模型错误的成本越高，验证要求也越严格。',
      '本项目把大模型主要放在信息抽取层：输出利好/中性/利空、分数、置信度与理由。真正的仓位仍由确定性的因子组合和回测代码产生，这样可以分别审计“模型读懂了什么”和“策略怎样使用它”。',
    ],
    visualTitle: 'AI 的三层职责与风险',
    flow: [
      { title: '工程助手', detail: '写代码、测试、文档；风险较低' },
      { title: '信息抽取', detail: '文本转字段；需要抽样复核' },
      { title: '预测模型', detail: '预测收益或方向；必须样本外验证' },
      { title: '组合决策', detail: '仓位与风险约束；最终由规则负责' },
    ],
    exampleTitle: '为什么保存 rationale',
    example: '一条公告被打成“利好 +0.65”时，页面同时展示简要理由和原文链接。你可以抽查模型是否引用了原文事实，而不是只信一个分数。',
    pitfalls: ['把模型置信度当成真实正确率', '让模型直接给买卖建议', '升级模型后不重新做一致性评估'],
    practice: ['列出当前项目中 AI 与非 AI 模块各两个', '说明情绪抽取为什么比直接预测股价更容易审计'],
  },
  'quant-map:2': {
    mentalModel: 'Web3 回答“资产和基础设施是什么”，量化回答“怎样用数据研究规则”；二者可以相交，但不是同义词。',
    deepDive: [
      '股票、期货、ETF、外汇和链上资产都可以被量化研究。Web3 特有的数据包括区块、交易、地址、智能合约事件和去中心化交易池状态，但研究流程仍然要处理时点、成本、流动性与样本外验证。',
      '本项目聚焦 A 股日频研究，因为数据语义、交易日历和财务披露已经足够复杂。掌握这条研究闭环后，再迁移到链上资产，主要变化是数据源、交易机制和风险边界，而不是推倒重来。',
    ],
    visualTitle: '资产世界与研究方法的交叉',
    flow: [
      { title: '传统资产', detail: '股票、ETF、期货、债券' },
      { title: '量化方法', detail: '数据、因子、回测、风险控制' },
      { title: '链上资产', detail: 'Token、DEX、借贷协议' },
    ],
    exampleTitle: '同一个动量思想',
    example: 'A 股动量使用交易日收盘价；链上动量可能使用 24×7 分钟价。公式相似，但后者还要考虑 Gas、MEV、池深度和智能合约风险。',
    pitfalls: ['把“AI + 区块链”当成自动可信', '忽略链上 24×7 与股票交易日历差异', '把 Token 流动性当成股票盘口'],
    practice: ['写出 A 股与链上资产各三个数据字段', '找出两类市场中交易成本含义的差异'],
  },
  'project-tour:0': {
    mentalModel: '把当前代码库映射成你熟悉的分层 Web 系统，只是领域对象从订单、用户换成行情、因子和实验。',
    deepDive: [
      'FastAPI 的 router 类似 Spring Controller，Pydantic Schema 类似带运行时校验的 DTO，SQLAlchemy Model 类似 JPA Entity，services 承载领域逻辑。React 页面通过统一 api 函数调用后端，不直接接触 MySQL。',
      '不同于普通 CRUD，量化系统有大量长耗时和可重复计算。API 只创建任务，Worker 从 MySQL 队列认领后执行，进度和结果持续写回数据库。这使网页刷新、服务重启或跨设备访问都不会丢失任务状态。',
    ],
    visualTitle: '从浏览器到研究结果',
    flow: [
      { title: 'React', detail: '表单、图表、学习页面' },
      { title: 'FastAPI', detail: '校验请求并创建任务' },
      { title: 'MySQL 队列', detail: '持久化输入、状态和进度' },
      { title: 'Worker', detail: '运行采集、模型与回测服务' },
      { title: '结果表', detail: '页面读取并可视化' },
    ],
    exampleTitle: 'Java 经验如何复用',
    example: '你熟悉的 Controller → Service → Repository 分层仍然成立；新增的重点是 pandas 时间序列语义、任务幂等和研究结果可复现。',
    pitfalls: ['在 React 中实现回测核心逻辑', '让 HTTP 请求等待几分钟', '路由层直接堆积数据处理代码'],
    practice: ['从 App.tsx 找到任务中心对应的后端 router', '画出一次“运行回测”的调用链'],
  },
  'project-tour:1': {
    mentalModel: '任务是一份可审计的工作订单：payload 是输入快照，status 是状态机，result/error 是执行证据。',
    deepDive: [
      '创建任务时只写 queued；Worker 使用数据库锁认领最早且优先级最高的任务，改成 running 后再执行。成功写 result，失败记录 error；达到最大重试次数前可以重新排队。',
      '任务队列不是为了追求极致吞吐，而是让 2 核 2G 的教学服务器稳定工作。单 Worker 串行执行可避免同时跑数据采集、模型分析和回测造成内存峰值，也更容易追查失败。',
    ],
    visualTitle: '研究任务状态机',
    flow: [
      { title: 'queued', detail: '请求已持久化，等待认领' },
      { title: 'running', detail: 'Worker 已锁定并更新进度' },
      { title: 'success', detail: '结果完整保存' },
      { title: 'failed', detail: '错误与尝试次数保留' },
      { title: 'retry', detail: '可恢复错误重新排队' },
    ],
    exampleTitle: '自动舆情流水线',
    example: '调度器每 6 小时先创建新闻公告同步任务，再创建情绪分析任务。优先级保证采集先执行，分析随后消费新增事件。',
    pitfalls: ['重试时重复插入同一条新闻', '任务失败只写日志不写数据库', '多个 Worker 无锁认领同一任务'],
    practice: ['在任务中心手动创建一项数据质量任务并观察状态变化', '说明 max_attempts 与 attempts 的区别'],
  },
  'project-tour:2': {
    mentalModel: '原始事实、派生特征和实验结果要分层保存，任何结论都应能沿数据血缘向前追溯。',
    deepDive: [
      '行情、新闻、公告和财务披露是源数据；情绪分、动量和质量分是派生数据；回测与 Walk-forward 是实验结果。分表让你可以重新计算模型输出而不重复抓取源数据，也能比较不同模型版本。',
      '每层都需要业务唯一键：行情用股票+交易日，新闻用内容哈希，情绪分析用 news_id，因子分数用股票+评分日。唯一键既是数据模型，也是任务幂等的基础。',
    ],
    visualTitle: '研究数据分层',
    flow: [
      { title: 'Bronze 原始层', detail: '行情、公告、新闻、披露' },
      { title: 'Silver 清洗层', detail: '交易日对齐、去重、点时化' },
      { title: 'Gold 因子层', detail: '动量、质量、情绪分数' },
      { title: 'Experiment', detail: '回测、样本外与报告' },
    ],
    exampleTitle: '为什么不把情绪直接写回新闻表',
    example: '独立的 sentiment_analyses 表能保存模型名与分析时间。将来升级模型时可以明确哪些结果需要重算，而不污染原始新闻。',
    pitfalls: ['派生字段覆盖原始字段', '缺少 source 和时间戳', '所有 JSON 都塞进一张万能表'],
    practice: ['为 aq_daily_prices 找出业务唯一键', '解释 aq_factor_scores 为什么还需要 score_date'],
  },
  'python-bridge:0': {
    mentalModel: 'Python 的短小来自运行时协议与引用语义，不是“没有类型”；从 Java 迁移时最应防的是默认共享状态和隐式真值。',
    deepDive: [
      '变量保存对象引用，不声明固定类型。list、dict 等可变对象被多个变量引用时，任何一处修改都会被看见；函数默认参数只在定义时计算一次，因此不能用 [] 作为会被修改的默认值。',
      '类型提示帮助 IDE、检查器和读者，但运行时通常不会自动阻止错误类型。项目用 Pydantic 在 API 边界做强校验，在内部用类型提示和测试维持契约。',
    ],
    visualTitle: '一次 Python 赋值发生了什么',
    flow: [
      { title: '对象', detail: 'list / dict 可变，str / tuple 不可变' },
      { title: '引用', detail: '变量名指向对象而非容器副本' },
      { title: '协议', detail: 'truthiness、迭代与上下文管理' },
      { title: '边界校验', detail: 'Pydantic 把外部输入转成可信对象' },
    ],
    exampleTitle: '可变默认参数陷阱',
    example: '如果 def add(item, bucket=[]) 把 item 追加到 bucket，下一次调用会看到上次内容。正确做法是 bucket=None，再在函数内创建新列表。',
    code: `def add(item: str, bucket: list[str] | None = None) -> list[str]:\n    result = [] if bucket is None else bucket\n    result.append(item)\n    return result`,
    pitfalls: ['用 is 比较普通字符串或数字', '认为类型提示会自动运行时校验', '在函数默认参数中放可变对象'],
    practice: ['运行 learning/examples/01_python_bridge.py', '用 id() 观察两个变量是否引用同一个 list'],
  },
  'python-bridge:1': {
    mentalModel: 'Pythonic 不是把代码压成一行，而是使用语言协议表达意图，并把大规模数值循环交给 NumPy/pandas。',
    deepDive: [
      'enumerate 同时给索引和值，zip 对齐多组迭代对象，推导式适合简单映射和过滤，dataclass 适合承载有明确字段的数据。复杂业务分支仍应写成命名清楚的函数。',
      'with 语句通过上下文管理器保证资源释放。数据库 Session、文件、锁和 HTTP Client 都适合用它管理，即使中途抛异常也会执行退出逻辑。',
    ],
    visualTitle: '从逐条脚本到表达式',
    flow: [
      { title: '迭代协议', detail: 'for / enumerate / zip' },
      { title: '小型转换', detail: '推导式与生成器' },
      { title: '批量数值', detail: 'NumPy / pandas 向量化' },
      { title: '资源生命周期', detail: 'with 自动清理' },
    ],
    exampleTitle: '股票代码规范化',
    example: 'list(dict.fromkeys(...)) 可以在保持顺序的同时去重；但如果逻辑再增加市场映射和错误报告，就应拆成清楚的 normalize_symbols 函数。',
    code: `symbols = list(dict.fromkeys(\n    symbol.strip() for symbol in raw_symbols if symbol.strip()\n))`,
    pitfalls: ['为了“一行代码”牺牲可读性', '对 DataFrame 使用逐行 for 循环', '忘记关闭数据库或文件资源'],
    practice: ['把一个 Java for 循环改写为 enumerate', '比较列表推导式与生成器在内存上的差异'],
  },
  'python-bridge:2': {
    mentalModel: 'Traceback 是一条调用路径，不是噪声；测试则是把已经理解的错误变成以后不会复发的契约。',
    deepDive: [
      '先读 traceback 最后一行确定异常类型和消息，再向上找到第一个属于本项目的文件与行号。ValueError 往往是值不合法，TypeError 是类型或调用方式不匹配，KeyError/IndexError 是访问不存在的键或位置。',
      'pytest 测试应覆盖边界和金融语义，例如信号必须 shift(1)、手续费只在换仓时扣除、最大回撤从历史峰值计算。它们比“函数能运行”更接近真实正确性。',
    ],
    visualTitle: '从故障到回归测试',
    flow: [
      { title: '复现', detail: '固定最小输入与环境' },
      { title: '定位', detail: '从异常类型回到项目入口' },
      { title: '解释', detail: '找根因而非只消除报错' },
      { title: '测试', detail: '把失败场景写成断言' },
      { title: '修复', detail: '确认新旧用例都通过' },
    ],
    exampleTitle: '收益错位测试',
    example: '构造三天价格，让第二天才产生信号。断言策略收益只能从第三天开始出现，就能防止未来数据被当天交易使用。',
    pitfalls: ['只复制最后一行错误去搜索', '通过 try/except 吞掉未知异常', '测试只验证 HTTP 200，不验证数值语义'],
    practice: ['故意给 StrategyParameters 传入错误权重并阅读异常', '为一个已知边界补一条 pytest 断言'],
  },
  'numpy-pandas:0': {
    mentalModel: 'NumPy 是按 shape、dtype、axis 运算的数值数组；pandas 在数组上增加标签、缺失值和表格语义。',
    deepDive: [
      'axis=0 通常沿行聚合得到每列结果，axis=1 沿列聚合得到每行结果。dtype 决定精度、内存和可用操作；混入字符串可能把数值列变成 object，性能和行为都会改变。',
      '向量化意味着把整列交给底层实现，而不是在 Python 中逐单元格执行。收益率、滚动均线和横截面排名都应优先使用 pct_change、rolling、rank 等操作。',
    ],
    visualTitle: '数组到带标签表格',
    flow: [
      { title: 'ndarray', detail: 'shape + dtype + axis' },
      { title: 'Series', detail: '一维数值 + index' },
      { title: 'DataFrame', detail: '多列 Series 按 index 对齐' },
      { title: '向量化', detail: '整列运算与底层循环' },
    ],
    exampleTitle: '计算日收益',
    example: 'close.pct_change() 会得到当前收盘价相对上一行的变化。第一行没有上一日，因此 NaN 是正确含义，不应随意填成某个“真实收益”。',
    code: `prices = prices.sort_index()\nreturns = prices["close"].pct_change()\nvolatility = returns.rolling(20).std()`,
    pitfalls: ['忽略 dtype=object', '弄反 axis 含义', '把所有 NaN 都填成 0'],
    practice: ['查看一组 OHLCV DataFrame 的 shape 与 dtypes', '分别沿 axis=0 和 axis=1 求均值并解释结果'],
  },
  'numpy-pandas:1': {
    mentalModel: 'pandas 的运算按标签对齐；这既能保护时间语义，也会在索引不一致时产生必须解释的 NaN。',
    deepDive: [
      '两个 Series 相加时，pandas 先取索引并集，再对同标签做运算。股票 A 缺少某交易日时不会自动把下一行错配过去。日期应先转 DatetimeIndex、排序、去重，再与交易日历比较。',
      'reindex 到完整交易日历后出现的空值，可能是停牌、采集失败或上市前区间。三种情况处理不同，所以填充前必须知道缺失原因。',
    ],
    visualTitle: '时间对齐的判断路径',
    flow: [
      { title: '解析日期', detail: '统一时区与日期类型' },
      { title: '排序去重', detail: '保证索引单调且唯一' },
      { title: '交易日历', detail: '区分休市与应有数据' },
      { title: '对齐', detail: '按标签合并，不按位置硬拼' },
      { title: '解释缺失', detail: '停牌、缺采或范围外' },
    ],
    exampleTitle: '为什么需要 aq_trading_calendar',
    example: '周日没有价格不是数据问题；周三全市场开市但某只正常交易股票没有记录，才可能触发数据质量告警。',
    pitfalls: ['按行号合并不同股票', '日期字符串未排序就 rolling', '看到 NaN 就 forward-fill'],
    practice: ['构造两个日期不完全相同的 Series 并相加', '用交易日历识别一个真正的行情缺口'],
  },
  'numpy-pandas:2': {
    mentalModel: 'rolling 只看窗口内的历史，shift 决定信息何时可交易；二者组合是避免未来函数的核心。',
    deepDive: [
      'rolling(20).mean() 在第 t 行包含第 t 日收盘价，表示收盘后才能知道的指标。如果策略假设下一交易日执行，就必须把由它产生的仓位 shift(1) 后再乘第 t 日收益。',
      'rolling 默认需要足够样本，前 19 行会是 NaN。降低 min_periods 虽可提前产生值，但统计含义改变，必须作为显式研究选择而不是“修复空值”。',
    ],
    visualTitle: '信号与执行的时间线',
    flow: [
      { title: 't 日收盘', detail: '价格正式确定' },
      { title: '计算因子', detail: 'rolling 窗口包含 t 日' },
      { title: '生成信号', detail: '收盘后才能获得' },
      { title: 'shift(1)', detail: '推迟为 t+1 日持仓' },
      { title: '计算收益', detail: '持仓 × 下一周期收益' },
    ],
    exampleTitle: '最小可信回测',
    example: '今天收盘价站上均线，只能决定明天是否持有。若直接用今天信号乘今天收益，就把已经发生的涨幅据为己有。',
    code: `signal = (close > close.rolling(20).mean()).astype(float)\nposition = signal.shift(1).fillna(0)\nstrategy_return = position * close.pct_change()`,
    pitfalls: ['当日信号乘当日收益', '用 centered rolling 平滑交易信号', '随意设置 min_periods=1'],
    practice: ['手算四天价格的 signal 与 position', '运行 learning/examples/03_signal_delay.py'],
  },
  'market-data:0': {
    mentalModel: '同一只股票有原始价、前复权和后复权等不同坐标系；研究前必须固定口径。',
    deepDive: [
      '分红、送股和拆股会让原始价格出现非交易原因的跳变。前复权通常调整历史价格以保持当前价，适合观察历史收益连续性；后复权则把后续权益累积到当前。不同源算法也可能略有差异。',
      'OHLCV 还包含成交可行性信息：停牌、涨跌停、极低成交额都可能让理论仓位无法成交。第一版日频回测可以简化，但必须在报告里写明限制。',
    ],
    visualTitle: '价格数据进入研究前的检查',
    flow: [
      { title: '原始 OHLCV', detail: '交易所记录与企业行动' },
      { title: '复权口径', detail: '选择 qfq / hfq 并保持一致' },
      { title: '交易日对齐', detail: '识别停牌和缺口' },
      { title: '可成交规则', detail: '成本、涨跌停与流动性' },
      { title: '基准对齐', detail: '相同区间与频率' },
    ],
    exampleTitle: '除权日的假动量',
    example: '若一只股票因分红除权价格机械下跌，原始价可能产生巨大负收益；使用一致复权数据可避免把企业行动误判为市场崩跌。',
    pitfalls: ['close 用前复权、open 用原始价', '不同股票使用不同复权口径', '忽略停牌时无法调仓'],
    practice: ['对同一股票比较 raw/qfq/hfq 曲线', '找一个除权日并解释三种价格变化'],
  },
  'market-data:1': {
    mentalModel: '收益回答增长，回撤回答路径痛苦，波动和夏普回答风险效率；任何一个指标都不能单独代表好策略。',
    deepDive: [
      '累计收益由每日净值连乘得到，年化收益应基于完整持有期的复利。最大回撤是资金曲线相对此前峰值的最深跌幅，能揭示投资者在恢复前承受的损失。',
      '夏普通常用平均超额收益除以收益标准差，再按频率年化。它假设频率一致并对异常值敏感；对非正态、低频或收益自相关策略，还应结合回撤和分期结果解读。',
    ],
    visualTitle: '从日收益到研究结论',
    flow: [
      { title: '日净收益', detail: '毛收益减交易成本' },
      { title: '资金曲线', detail: '逐期复利累计' },
      { title: '收益指标', detail: '累计与年化' },
      { title: '风险指标', detail: '波动、回撤、尾部损失' },
      { title: '对比', detail: '同区间基准与样本外' },
    ],
    exampleTitle: '两个策略如何选择',
    example: '策略 A 年化 18%、最大回撤 45%；策略 B 年化 13%、最大回撤 12%。不能只凭年化判定 A 更优，还要结合目标、波动和恢复时间。',
    code: `equity = (1 + returns).cumprod()\ndrawdown = equity / equity.cummax() - 1\nmax_drawdown = drawdown.min()`,
    pitfalls: ['短期收益直接乘 252', '用价格而非资金曲线算回撤', '拿不同区间的策略和基准比较'],
    practice: ['手算一条五期资金曲线的最大回撤', '说明夏普相同的两个策略仍可能有哪些差异'],
  },
  'market-data:2': {
    mentalModel: '财务数据的关键不是报告期，而是市场何时真正获得它；回测只能使用 available_at 不晚于评分日的版本。',
    deepDive: [
      '2025 年年报的 report_date 可能是 2025-12-31，但公告到 2026 年 3 月才发布。若在 2026 年 1 月回测中使用该年报，就发生了未来数据泄漏。',
      '真实数据库还会出现预告、快报、正式报告和修订。点时模型应保存 report_date、available_at、source 和是否估算，在每个评分日选择当时最新可得记录。',
    ],
    visualTitle: '报告期与可用时间',
    flow: [
      { title: '经营期间', detail: '业务发生在 2025 年' },
      { title: '报告期末', detail: 'report_date=2025-12-31' },
      { title: '编制审计', detail: '市场尚未知完整数字' },
      { title: '公告发布', detail: 'available_at=披露日' },
      { title: '进入因子', detail: '评分日必须不早于披露日' },
    ],
    exampleTitle: '点时查询条件',
    example: '在 2026-02-01 评分时，只选择 available_at <= 2026-02-01 的财务记录，并在同一指标中取最新披露版本。',
    code: `usable = financials[financials["available_at"] <= score_date]\nlatest = usable.sort_values("available_at").groupby("metric_name").tail(1)`,
    pitfalls: ['把 report_date 当成发布日期', '使用数据库里的最终修订值回填历史', '季度间简单 forward-fill 却不记录来源'],
    practice: ['画出一份年报从报告期到公告日的时间线', '在项目中找到 available_at 的筛选逻辑'],
  },
  'factor-backtest:0': {
    mentalModel: '因子是用于比较或预测的数值特征，信号是参与规则，仓位才是资金真正承担的暴露。',
    deepDive: [
      '时间序列信号比较同一资产当前与过去，例如动量是否大于 0；横截面信号在同一天比较多只股票，例如选总分前 3。两类判断组合后，再应用空仓、单票上限和等权规则。',
      '因子量纲不同，组合前常需排名、标准化或压缩到统一范围。本项目把动量、质量和情绪映射成分数，再按可配置权重合成 total_score。',
    ],
    visualTitle: '因子如何变成可执行仓位',
    flow: [
      { title: '原始特征', detail: '收益、财务、情绪事件' },
      { title: '因子分数', detail: '统一方向和尺度' },
      { title: '门槛', detail: '决定是否参与' },
      { title: '排序 Top N', detail: '决定持有哪些股票' },
      { title: '目标权重', detail: '等权或风险约束' },
    ],
    exampleTitle: '双因子并不等于相加完就买',
    example: '某股票总分最高，但动量仍为负时，可以由 minimum_momentum 规则将其排除。这个门槛体现“评分”和“参与条件”的区别。',
    pitfalls: ['把因子值直接当成持仓比例', '组合前忽略量纲', '权重之和不等于 1 或没有现金仓位定义'],
    practice: ['给三只股票手算加权总分和 Top 2', '设计一个全市场都不满足门槛时的空仓规则'],
  },
  'factor-backtest:1': {
    mentalModel: '交易成本由仓位变化产生，不由“持有”产生；换手越高，策略越依赖理想化成交。',
    deepDive: [
      '若昨日权重 0.2、今日目标权重 0.5，单边换手是 0.3。组合总换手通常对所有资产权重变化取绝对值后求和，再按成本定义决定是否除以 2。',
      '手续费、印花税、滑点和冲击成本并不完全对称。教学版可用统一费率，但报告必须说明公式。高频调仓策略应做成本敏感性测试，看收益在成本翻倍后是否仍存在。',
    ],
    visualTitle: '净收益的扣费路径',
    flow: [
      { title: '昨日仓位', detail: '实际持有权重' },
      { title: '今日目标', detail: '因子产生的新权重' },
      { title: '换手', detail: '目标减实际的绝对变化' },
      { title: '成本', detail: '手续费 + 滑点 + 冲击' },
      { title: '净收益', detail: '毛收益减成本' },
    ],
    exampleTitle: '调仓频率的代价',
    example: '同一个信号每日调仓可能毛收益更高，但周频调仓的换手更低。扣费后结果反转，说明策略优势不足以覆盖执行摩擦。',
    code: `turnover = weights.diff().abs().sum(axis=1)\ncost = turnover * (fee_rate + slippage_rate)\nnet_return = gross_return - cost`,
    pitfalls: ['只在买入时扣成本', '信号不变也重复扣费', '忽略策略规模增大后的冲击成本'],
    practice: ['手算两资产从 50/50 到 100/0 的换手', '把成本提高一倍观察回测是否稳健'],
  },
  'factor-backtest:2': {
    mentalModel: '回测泄漏的本质是让历史中的决策者知道了当时不知道的事，或只保留今天幸存的数据。',
    deepDive: [
      '未来数据泄漏包括当日收盘信号当日成交、使用未来财务、全样本标准化；幸存者偏差来自只研究今天仍上市的股票；修订偏差来自用最终数据替代历史版本；参数过拟合来自反复看测试结果。',
      '防护不是一条 shift(1) 就结束。需要交易日历、点时财务、发布时间、股票历史成分、固定参数网格和独立样本外窗口共同形成证据链。',
    ],
    visualTitle: '四类泄漏与防线',
    flow: [
      { title: '时间泄漏', detail: 'shift + 发布时间边界' },
      { title: '幸存者偏差', detail: '历史股票池与退市样本' },
      { title: '修订偏差', detail: '保存数据版本和 available_at' },
      { title: '参数窥探', detail: '预注册网格与样本外测试' },
    ],
    exampleTitle: '一个隐蔽的全样本标准化',
    example: '先用 2018–2026 全部数据的均值和标准差计算 z-score，再切训练测试，会把未来分布泄漏给过去。正确做法是在每个训练窗口拟合缩放参数。',
    pitfalls: ['只检查价格 shift 不检查财务时点', '用当前沪深300成分回测十年前', '测试集上反复调阈值'],
    practice: ['对当前回测逐项检查四类泄漏', '写下每项防线对应的代码或数据表'],
  },
  'sentiment-llm:0': {
    mentalModel: '大模型输出必须像 API 数据一样有 Schema、范围和审计证据，而不是一段看似专业的散文。',
    deepDive: [
      'label 只有利好/中性/利空，score 固定在 [-1,1]，confidence 固定在 [0,1]，summary 和 rationale 限长。后端仍需解析、截断、夹紧范围并处理非法标签，不能因为模型“承诺 JSON”就省略校验。',
      'prompt 约束模型只基于给定文本，不补充外部事实、不输出买卖建议。rationale 用于人工复核，但真正的数据血缘还包括原文链接、模型名和分析时间。',
    ],
    visualTitle: '文本变成情绪因子的管道',
    flow: [
      { title: '原始事件', detail: '标题、正文、来源、发布时间' },
      { title: 'Prompt', detail: '任务边界与 JSON Schema' },
      { title: 'LLM', detail: 'Thinking 后输出结构化判断' },
      { title: '校验', detail: '枚举、范围、长度、解析' },
      { title: '落库', detail: '分数、理由、模型与时间' },
    ],
    exampleTitle: '为什么 score 与 confidence 分开',
    example: 'score=-0.8 表示影响方向和强度偏负；confidence=0.45 表示模型对这个判断并不十分确信。二者不能相互替代。',
    pitfalls: ['解析失败就把整段文本当分数', '允许模型引用输入外事实', '把 confidence 当成统计校准后的正确概率'],
    practice: ['为一条公告手工填写完整 Schema', '构造非法 label 并观察后端如何规范化'],
  },
  'sentiment-llm:1': {
    mentalModel: '事件因子的第一条规则是时间因果：只有 published_at 已经发生的内容才能影响当前评分，且旧事件影响应逐渐减弱。',
    deepDive: [
      '抓取时间 fetched_at 不能替代发布时间 published_at。旧公告今天被重新抓到，不能算成今天的新利好；同一内容也要用稳定哈希去重，避免重复放大。',
      '指数衰减常用 weight=exp(-age/half_life) 或 0.5^(age/half_life)。半衰期表示经过该时间后权重减半，适合表达新闻冲击逐步消退，但参数仍需样本外验证。',
    ],
    visualTitle: '事件从发布到失效',
    flow: [
      { title: 'published_at', detail: '市场首次可知时刻' },
      { title: '去重', detail: 'content_hash 阻止重复计数' },
      { title: '窗口筛选', detail: '只取评分日前的近期事件' },
      { title: '时间衰减', detail: '越近权重越高' },
      { title: '聚合', detail: '按股票形成情绪因子' },
    ],
    exampleTitle: '7 日情绪窗口',
    example: '评分日回看 7 天事件，对 1 天前利好赋较高权重，对 6 天前事件赋较低权重；8 天前事件不再进入本次因子。',
    code: `age_days = (score_date - published_at.date()).days\nweight = 0.5 ** (age_days / half_life_days)\nweighted_score = score * confidence * weight`,
    pitfalls: ['用抓取时间代替发布时间', '重复转载被累计多次', '未来时区转换错误让晚间公告提前一天'],
    practice: ['计算半衰期 3 天时第 0/3/6 天权重', '在新闻表中比较 published_at 与 fetched_at'],
  },
  'sentiment-llm:2': {
    mentalModel: '模型评估要同时看标签质量、分数稳定性和进入策略后的增量价值，不能只看几个“说得很像”的案例。',
    deepDive: [
      '先建立人工标注小样本，计算三分类混淆矩阵、一致率和分数误差；再按新闻/公告、行业、文本长度和市场阶段分组。模型升级或 Prompt 修改后必须重跑同一评估集。',
      '即使标签准确，因子也可能没有交易价值。应比较“只有行情”与“行情+情绪”的样本外表现，并控制额外换手。模型成本、延迟和不可用回退也属于系统评估。',
    ],
    visualTitle: '从模型质量到策略价值',
    flow: [
      { title: '人工金标', detail: '明确标注规则和分歧' },
      { title: '离线指标', detail: '一致率、混淆矩阵、校准' },
      { title: '稳定性', detail: '模型/Prompt/分组对比' },
      { title: '因子检验', detail: '未来收益相关与衰减' },
      { title: '策略增量', detail: '样本外收益减成本' },
    ],
    exampleTitle: '备用 Key 不等于备用模型',
    example: '主 Key 配额不足时用备用 Key 继续请求同一 deepseek-v4-pro；若服务整体不可用，则回退规则分析并在 model 字段明确记录 heuristic-v1。',
    pitfalls: ['只展示正确案例', '模型更大就假设因子更好', '回退结果与 LLM 结果混在一起不标记'],
    practice: ['抽样 20 条事件人工复核', '设计一个“模型升级前后”对比表'],
  },
  'walk-forward:0': {
    mentalModel: 'Walk-forward 模拟真实研究节奏：只在过去选参数，把固定参数应用到紧接着的未来，然后向前滚动。',
    deepDive: [
      '每个窗口由训练段和测试段组成。训练段可比较候选参数，测试段只能运行胜出参数，不能再调整。最终资金曲线只拼接各窗口测试段收益。',
      '金融标签和特征窗口可能跨边界，因此有时需在训练与测试间留 gap。窗口长度是偏差—方差权衡：太短不稳定，太长又可能混入过时市场结构。',
    ],
    visualTitle: '滚动样本外窗口',
    flow: [
      { title: '训练 1', detail: '过去数据选择参数 A' },
      { title: '测试 1', detail: '未来固定使用 A' },
      { title: '训练 2', detail: '窗口前移重新选择' },
      { title: '测试 2', detail: '固定新参数运行' },
      { title: '拼接 OOS', detail: '只连接测试收益' },
    ],
    exampleTitle: '126/42 交易日设置',
    example: '用约半年训练数据选择动量窗口，再在约两个月测试。测试结束后整体前移 42 天，重复直到区间结束。',
    pitfalls: ['随机打乱时间序列', '把训练收益拼入最终曲线', '测试期表现差就现场换参数'],
    practice: ['在样本外验证页运行一次小窗口实验', '在结果中区分 train 与 test 指标'],
  },
  'walk-forward:1': {
    mentalModel: '参数搜索次数也是模型复杂度；你试得越多，偶然找到漂亮结果的概率越高。',
    deepDive: [
      '参数网格应在实验前定义，并限制在有经济含义的范围。选择目标不能只追最高收益，可使用“年化收益 - 回撤惩罚”或同时报告收益、夏普与回撤。',
      '测试集一旦被看过并用于修改参数，就不再是真正测试集。可以新增更晚的保留区间，或把每次实验及改动原因完整记录，承认有效独立样本正在减少。',
    ],
    visualTitle: '参数窥探如何发生',
    flow: [
      { title: '定义假设', detail: '事先限定参数范围' },
      { title: '训练选择', detail: '只在训练窗口比较' },
      { title: '冻结参数', detail: '进入测试前不再修改' },
      { title: '查看 OOS', detail: '用于评估而非再训练' },
      { title: '记录实验', detail: '保留搜索次数与失败结果' },
    ],
    exampleTitle: '20 个窗口 × 20 个阈值',
    example: '400 个组合中总会有几个看起来优秀。若没有多重比较意识和样本外窗口，最好的组合很可能只是噪声冠军。',
    pitfalls: ['不断扩大网格直到出现高收益', '删掉亏损窗口只展示平均值', '把同一测试集重复用于版本迭代'],
    practice: ['在运行前写下候选窗口与阈值', '统计自己实际比较了多少个组合'],
  },
  'walk-forward:2': {
    mentalModel: '负的样本外结果是有效信息：它可能诚实否定了假设，也可能暴露成本、数据或实现问题。',
    deepDive: [
      '先检查代码和数据完整性，再看训练与测试落差、各窗口参数稳定性、交易次数和回撤。如果训练优秀但多数测试亏损，优先怀疑过拟合；若训练测试都差，假设本身可能无效。',
      '最终结论应区分统计事实和解释：事实是“8 个窗口中 6 个为负”，解释可能是“情绪衰减过慢”，后者还需新实验验证。',
    ],
    visualTitle: '样本外结果诊断树',
    flow: [
      { title: '数据正确？', detail: '缺口、时间与复权检查' },
      { title: '实现正确？', detail: '信号延迟与成本测试' },
      { title: '训练稳定？', detail: '参数和指标是否漂移' },
      { title: 'OOS 稳定？', detail: '窗口分布与市场阶段' },
      { title: '形成结论', detail: '接受、否定或继续验证' },
    ],
    exampleTitle: '为什么 -12.7% 不一定是 Bug',
    example: '若基准同期也大跌且策略回撤更小，负收益仍可能体现防守价值；若训练期大赚而测试期普遍亏损，则更像过拟合证据。',
    pitfalls: ['把亏损自动归因于代码错误', '只看总 OOS 不看窗口分布', '用事后故事替代新验证'],
    practice: ['为一次样本外结果写“事实/推断/待验证”三栏', '比较策略与沪深300同区间回撤'],
  },
  'research-engineering:0': {
    mentalModel: '幂等意味着同一任务执行多次，最终业务状态与执行一次相同；可重试建立在这个性质之上。',
    deepDive: [
      '数据库自增 id 不能识别业务重复。行情用 symbol+trade_date，新闻用 content_hash，财务用 symbol+report_date+available_at+metric_name 建唯一约束，重复同步时执行 upsert。',
      '并非所有字段都适合更新。原始来源时间、人工标记和真实数据不能被演示种子覆盖；任务开始前应明确插入、更新、忽略和冲突规则。',
    ],
    visualTitle: '安全重试的四道防线',
    flow: [
      { title: '稳定业务键', detail: '定义什么叫同一条记录' },
      { title: '事务', detail: '一组写入要么成功要么回滚' },
      { title: 'Upsert 策略', detail: '明确哪些字段可覆盖' },
      { title: '任务状态', detail: '记录尝试、错误和结果' },
    ],
    exampleTitle: '新闻重复抓取',
    example: '相同标题、正文和来源生成相同哈希，数据库唯一约束阻止重复插入。重跑同步任务不会把同一利好累计两次。',
    pitfalls: ['把自增 id 当幂等键', '捕获冲突后静默丢弃所有更新', '失败重试前不回滚事务'],
    practice: ['找出三个数据表的 UniqueConstraint', '重复运行一次种子或同步并比较记录数'],
  },
  'research-engineering:1': {
    mentalModel: '数据质量是一组带证据和生命周期的规则，不是单个 is_valid 布尔值。',
    deepDive: [
      'OHLC 合法性、交易日缺口、过期数据、异常跳变和覆盖率属于不同类别，也有不同严重性。每个问题应记录实体、阈值、实际值、首次和最近发现时间。',
      '相同问题重复检查时应更新 last_seen_at 而不是新增告警；问题消失时写 resolved_at。这样页面能区分当前问题、历史问题和反复出现的问题。',
    ],
    visualTitle: '一条质量告警的生命周期',
    flow: [
      { title: '规则运行', detail: '按实体计算证据' },
      { title: '指纹', detail: '类别 + 实体形成稳定标识' },
      { title: '发现', detail: '记录首次/最近时间' },
      { title: '持续', detail: '重复出现只更新状态' },
      { title: '解决', detail: '规则恢复后标记 resolved' },
    ],
    exampleTitle: 'OHLC 合法性',
    example: '最高价应不低于 open/close/low，最低价应不高于 open/close/high。违反时记录日期和实际四价，便于回到数据源核查。',
    pitfalls: ['所有异常都标 critical', '只发日志不保存证据', '阈值写死且无业务解释'],
    practice: ['在数据治理页运行检查并阅读一条 evidence', '为成交量负数设计规则和严重性'],
  },
  'research-engineering:2': {
    mentalModel: '配置是可公开审查的运行参数，秘密是必须隔离的凭证；二者都不应硬编码在业务逻辑里。',
    deepDive: [
      '模型名、调度间隔、股票池和策略权重属于配置；数据库密码、API Key 和 SSH 密码属于秘密。配置可以进入数据库或环境变量，秘密只放在忽略文件或服务器权限受控的环境文件。',
      '日志、异常、截图和任务 payload 都可能泄密。系统只向前端返回“备用 Key 已配置”这样的布尔状态，不返回 Key 内容；部署脚本打包时也排除 credentials.txt 与 .env。',
    ],
    visualTitle: '配置从本地到服务器',
    flow: [
      { title: 'credentials.txt', detail: '本机忽略文件保存秘密' },
      { title: '部署脚本', detail: '只读取并生成受限 app.env' },
      { title: 'systemd', detail: '服务注入环境变量' },
      { title: '应用配置', detail: 'Pydantic 校验参数' },
      { title: '页面', detail: '只展示非敏感状态' },
    ],
    exampleTitle: '可热更新的 6 小时调度',
    example: '运行间隔保存在 aq_automation_settings，页面修改后后端即时重排 APScheduler；API Key 仍留在 app.env，不进入数据库或响应。',
    pitfalls: ['把 Token 提交到 Git', '异常信息打印完整 Authorization header', '把所有配置都做成可由网页修改'],
    practice: ['检查 git status 确认 credentials.txt 不被跟踪', '列出当前系统中三项配置和三项秘密'],
  },
  'capstone:0': {
    mentalModel: '毕业项目的目标不是证明自己能赚钱，而是交付一条可复现、可否定、边界清楚的研究证据链。',
    deepDive: [
      '先限制研究空间：固定股票池、日期、基准、交易成本、候选参数和样本外方案。研究前写成功与失败判据，避免看到结果后移动目标。',
      '代码、配置、数据质量报告、实验记录和结论缺一不可。即使结果否定策略，只要过程可信，毕业项目仍然成功。',
    ],
    visualTitle: '可信毕业项目验收链',
    flow: [
      { title: '预注册', detail: '假设、范围和判据' },
      { title: '数据证明', detail: '来源、时点与质量' },
      { title: '实现证明', detail: '测试、延迟与成本' },
      { title: '验证证明', detail: '基准与 Walk-forward' },
      { title: '结论边界', detail: '局限和下一步' },
    ],
    exampleTitle: '一个合格题目',
    example: '“在 15 只固定 A 股上，7 日衰减情绪是否能在 20 日动量策略基础上改善 2024–2026 样本外回撤？”比“做一个 AI 选股系统”更可验证。',
    pitfalls: ['题目过大且不断加股票', '把最高收益当唯一验收标准', '结果不好就更换区间'],
    practice: ['写下毕业题目、股票池和时间区间', '定义三个成功/失败指标'],
  },
  'capstone:1': {
    mentalModel: '研究报告是可执行实验的说明书，也是区分事实、推断和局限的审计记录。',
    deepDive: [
      '摘要先回答研究问题、方法和主要结论；数据部分说明来源、复权、时间边界与缺失处理；方法部分给出因子、仓位、成本和参数选择；结果同时展示基准、回撤和分窗口表现。',
      '稳健性部分报告成本敏感性、参数邻域和不同阶段；局限部分主动说明数据质量、成交简化、模型漂移与样本量。失败实验也要进入附录。',
    ],
    visualTitle: '一份研究报告的阅读路径',
    flow: [
      { title: '问题与摘要', detail: '为什么研究、结论是什么' },
      { title: '数据与时点', detail: '当时能知道什么' },
      { title: '方法与实现', detail: '如何产生仓位' },
      { title: '结果与稳健性', detail: '是否胜过基准且稳定' },
      { title: '局限与复现', detail: '哪里不能推广、怎样重跑' },
    ],
    exampleTitle: '事实与解释分开写',
    example: '事实：“加入情绪后 OOS 最大回撤从 18% 降到 14%”；解释：“负面公告过滤可能减少下跌暴露”。第二句仍需分组实验支持。',
    pitfalls: ['只放最终资金曲线', '隐藏失败参数和窗口', '没有写数据截止日期与模型版本'],
    practice: ['用八个标准章节建立报告目录', '为一张资金曲线写事实与解释各一句'],
  },
  'capstone:2': {
    mentalModel: '最终成果是一套可以继续学习和迭代的研究平台：页面、API、任务、数据、测试、部署和文档共同组成。',
    deepDive: [
      '成果应能在新环境一键部署，跨设备保存学习进度，定时采集与分析，运行回测和 Walk-forward，并在数据治理页说明可信度。Git 提交记录提供代码演进证据。',
      '进入模拟交易前，还需更严格的数据授权、实时性、故障恢复、监控和风险限制；进入实盘则需要券商接口、权限隔离和人工熔断。当前项目刻意停在研究边界。',
    ],
    visualTitle: '从学习者到研究系统',
    flow: [
      { title: '学会概念', detail: '章节、详情、Demo 与测验' },
      { title: '读懂项目', detail: '前后端、数据库和 Worker' },
      { title: '完成实验', detail: '因子、回测与样本外' },
      { title: '形成报告', detail: '证据、局限与复现' },
      { title: '安全迭代', detail: '模拟优先，不直接实盘' },
    ],
    exampleTitle: '可展示的毕业成果',
    example: '一条公开访问的研究站点、一份固定参数的样本外报告、一组自动化测试、一次数据质量运行和一个可复现的 Git 提交共同构成答辩材料。',
    pitfalls: ['功能多但没有可信实验', '部署成功就等于研究完成', '过早接入真实账户和自动下单'],
    practice: ['按页面逐项演示完整研究闭环', '列出进入模拟交易前仍缺少的五项能力'],
  },
}

export function lessonKey(chapterId: string, conceptIndex: number): string {
  return `${chapterId}:${conceptIndex}`
}
